/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedIdiomsIndexRouteImport } from './routes/_authenticated/idioms/index'
import { Route as AuthenticatedGameAssistGuessIdiomIndexRouteImport } from './routes/_authenticated/game-assist/guess-idiom/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIdiomsIndexRoute =
  AuthenticatedIdiomsIndexRouteImport.update({
    id: '/idioms/',
    path: '/idioms/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGameAssistGuessIdiomIndexRoute =
  AuthenticatedGameAssistGuessIdiomIndexRouteImport.update({
    id: '/game-assist/guess-idiom/',
    path: '/game-assist/guess-idiom/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/idioms/': typeof AuthenticatedIdiomsIndexRoute
  '/game-assist/guess-idiom/': typeof AuthenticatedGameAssistGuessIdiomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/idioms': typeof AuthenticatedIdiomsIndexRoute
  '/game-assist/guess-idiom': typeof AuthenticatedGameAssistGuessIdiomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/idioms/': typeof AuthenticatedIdiomsIndexRoute
  '/_authenticated/game-assist/guess-idiom/': typeof AuthenticatedGameAssistGuessIdiomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login/' | '/idioms/' | '/game-assist/guess-idiom/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/idioms' | '/game-assist/guess-idiom'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/login/'
    | '/_authenticated/idioms/'
    | '/_authenticated/game-assist/guess-idiom/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/idioms/': {
      id: '/_authenticated/idioms/'
      path: '/idioms'
      fullPath: '/idioms/'
      preLoaderRoute: typeof AuthenticatedIdiomsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/game-assist/guess-idiom/': {
      id: '/_authenticated/game-assist/guess-idiom/'
      path: '/game-assist/guess-idiom'
      fullPath: '/game-assist/guess-idiom/'
      preLoaderRoute: typeof AuthenticatedGameAssistGuessIdiomIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedIdiomsIndexRoute: typeof AuthenticatedIdiomsIndexRoute
  AuthenticatedGameAssistGuessIdiomIndexRoute: typeof AuthenticatedGameAssistGuessIdiomIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedIdiomsIndexRoute: AuthenticatedIdiomsIndexRoute,
  AuthenticatedGameAssistGuessIdiomIndexRoute:
    AuthenticatedGameAssistGuessIdiomIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
