/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as ForbiddenIndexRouteImport } from './routes/forbidden/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedAdminGameServersIndexRouteImport } from './routes/_authenticated/admin/game-servers/index'
import { Route as AuthenticatedAdminIdiomsIndexRouteImport } from './routes/_authenticated/admin/idioms/index'
import { Route as AuthenticatedAdminKungfusIndexRouteImport } from './routes/_authenticated/admin/kungfus/index'
import { Route as AuthenticatedAdminSchoolsIndexRouteImport } from './routes/_authenticated/admin/schools/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedGameAssistGuessIdiomIndexRouteImport } from './routes/_authenticated/game-assist/guess-idiom/index'
import { Route as AuthenticatedGameAssistMinesweeperIndexRouteImport } from './routes/_authenticated/game-assist/minesweeper/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ForbiddenIndexRoute = ForbiddenIndexRouteImport.update({
  id: '/forbidden/',
  path: '/forbidden/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminGameServersIndexRoute =
  AuthenticatedAdminGameServersIndexRouteImport.update({
    id: '/game-servers/',
    path: '/game-servers/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIdiomsIndexRoute =
  AuthenticatedAdminIdiomsIndexRouteImport.update({
    id: '/idioms/',
    path: '/idioms/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKungfusIndexRoute =
  AuthenticatedAdminKungfusIndexRouteImport.update({
    id: '/kungfus/',
    path: '/kungfus/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSchoolsIndexRoute =
  AuthenticatedAdminSchoolsIndexRouteImport.update({
    id: '/schools/',
    path: '/schools/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedGameAssistGuessIdiomIndexRoute =
  AuthenticatedGameAssistGuessIdiomIndexRouteImport.update({
    id: '/game-assist/guess-idiom/',
    path: '/game-assist/guess-idiom/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGameAssistMinesweeperIndexRoute =
  AuthenticatedGameAssistMinesweeperIndexRouteImport.update({
    id: '/game-assist/minesweeper/',
    path: '/game-assist/minesweeper/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/forbidden/': typeof ForbiddenIndexRoute
  '/login/': typeof LoginIndexRoute
  '/admin/game-servers/': typeof AuthenticatedAdminGameServersIndexRoute
  '/admin/idioms/': typeof AuthenticatedAdminIdiomsIndexRoute
  '/admin/kungfus/': typeof AuthenticatedAdminKungfusIndexRoute
  '/admin/schools/': typeof AuthenticatedAdminSchoolsIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/game-assist/guess-idiom/': typeof AuthenticatedGameAssistGuessIdiomIndexRoute
  '/game-assist/minesweeper/': typeof AuthenticatedGameAssistMinesweeperIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/forbidden': typeof ForbiddenIndexRoute
  '/login': typeof LoginIndexRoute
  '/admin/game-servers': typeof AuthenticatedAdminGameServersIndexRoute
  '/admin/idioms': typeof AuthenticatedAdminIdiomsIndexRoute
  '/admin/kungfus': typeof AuthenticatedAdminKungfusIndexRoute
  '/admin/schools': typeof AuthenticatedAdminSchoolsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/game-assist/guess-idiom': typeof AuthenticatedGameAssistGuessIdiomIndexRoute
  '/game-assist/minesweeper': typeof AuthenticatedGameAssistMinesweeperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/forbidden/': typeof ForbiddenIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/admin/game-servers/': typeof AuthenticatedAdminGameServersIndexRoute
  '/_authenticated/admin/idioms/': typeof AuthenticatedAdminIdiomsIndexRoute
  '/_authenticated/admin/kungfus/': typeof AuthenticatedAdminKungfusIndexRoute
  '/_authenticated/admin/schools/': typeof AuthenticatedAdminSchoolsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/game-assist/guess-idiom/': typeof AuthenticatedGameAssistGuessIdiomIndexRoute
  '/_authenticated/game-assist/minesweeper/': typeof AuthenticatedGameAssistMinesweeperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forbidden/'
    | '/login/'
    | '/admin/game-servers/'
    | '/admin/idioms/'
    | '/admin/kungfus/'
    | '/admin/schools/'
    | '/admin/users/'
    | '/game-assist/guess-idiom/'
    | '/game-assist/minesweeper/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/'
    | '/forbidden'
    | '/login'
    | '/admin/game-servers'
    | '/admin/idioms'
    | '/admin/kungfus'
    | '/admin/schools'
    | '/admin/users'
    | '/game-assist/guess-idiom'
    | '/game-assist/minesweeper'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/'
    | '/forbidden/'
    | '/login/'
    | '/_authenticated/admin/game-servers/'
    | '/_authenticated/admin/idioms/'
    | '/_authenticated/admin/kungfus/'
    | '/_authenticated/admin/schools/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/game-assist/guess-idiom/'
    | '/_authenticated/game-assist/minesweeper/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForbiddenIndexRoute: typeof ForbiddenIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/forbidden/': {
      id: '/forbidden/'
      path: '/forbidden'
      fullPath: '/forbidden/'
      preLoaderRoute: typeof ForbiddenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/game-servers/': {
      id: '/_authenticated/admin/game-servers/'
      path: '/game-servers'
      fullPath: '/admin/game-servers/'
      preLoaderRoute: typeof AuthenticatedAdminGameServersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/idioms/': {
      id: '/_authenticated/admin/idioms/'
      path: '/idioms'
      fullPath: '/admin/idioms/'
      preLoaderRoute: typeof AuthenticatedAdminIdiomsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kungfus/': {
      id: '/_authenticated/admin/kungfus/'
      path: '/kungfus'
      fullPath: '/admin/kungfus/'
      preLoaderRoute: typeof AuthenticatedAdminKungfusIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/schools/': {
      id: '/_authenticated/admin/schools/'
      path: '/schools'
      fullPath: '/admin/schools/'
      preLoaderRoute: typeof AuthenticatedAdminSchoolsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/game-assist/guess-idiom/': {
      id: '/_authenticated/game-assist/guess-idiom/'
      path: '/game-assist/guess-idiom'
      fullPath: '/game-assist/guess-idiom/'
      preLoaderRoute: typeof AuthenticatedGameAssistGuessIdiomIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/game-assist/minesweeper/': {
      id: '/_authenticated/game-assist/minesweeper/'
      path: '/game-assist/minesweeper'
      fullPath: '/game-assist/minesweeper/'
      preLoaderRoute: typeof AuthenticatedGameAssistMinesweeperIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminGameServersIndexRoute: typeof AuthenticatedAdminGameServersIndexRoute
  AuthenticatedAdminIdiomsIndexRoute: typeof AuthenticatedAdminIdiomsIndexRoute
  AuthenticatedAdminKungfusIndexRoute: typeof AuthenticatedAdminKungfusIndexRoute
  AuthenticatedAdminSchoolsIndexRoute: typeof AuthenticatedAdminSchoolsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminGameServersIndexRoute:
      AuthenticatedAdminGameServersIndexRoute,
    AuthenticatedAdminIdiomsIndexRoute: AuthenticatedAdminIdiomsIndexRoute,
    AuthenticatedAdminKungfusIndexRoute: AuthenticatedAdminKungfusIndexRoute,
    AuthenticatedAdminSchoolsIndexRoute: AuthenticatedAdminSchoolsIndexRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGameAssistGuessIdiomIndexRoute: typeof AuthenticatedGameAssistGuessIdiomIndexRoute
  AuthenticatedGameAssistMinesweeperIndexRoute: typeof AuthenticatedGameAssistMinesweeperIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGameAssistGuessIdiomIndexRoute:
    AuthenticatedGameAssistGuessIdiomIndexRoute,
  AuthenticatedGameAssistMinesweeperIndexRoute:
    AuthenticatedGameAssistMinesweeperIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForbiddenIndexRoute: ForbiddenIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
