import { betterAuth } from 'better-auth';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';
import { admin, openAPI } from 'better-auth/plugins';
import { db } from './db';

export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: 'pg',
  }),
  emailAndPassword: { enabled: true },
  session: {
    cookieCache: {
      enabled: true,
      maxAge: 7 * 24 * 60 * 60,
      strategy: 'jwt',
      refreshCache: true,
    },
  },
  account: {
    storeStateStrategy: 'cookie',
    storeAccountCookie: true,
  },
  plugins: [openAPI(), admin()],
});

let _schema: ReturnType<typeof auth.api.generateOpenAPISchema>;
const getSchema = async () => (_schema ??= auth.api.generateOpenAPISchema());
export const OpenAPI = {
  getPaths: (prefix = '/auth/api') =>
    getSchema().then(({ paths }) => {
      const reference: typeof paths = Object.create(null);
      for (const path of Object.keys(paths)) {
        const key = prefix + path;
        reference[key] = paths[path];
        for (const method of Object.keys(paths[path])) {
          // biome-ignore lint/suspicious/noExplicitAny: Code generated by Better Auth
          const operation = (reference[key] as any)[method];
          operation.tags = ['Better Auth'];
        }
      }
      return reference;
      // biome-ignore lint/suspicious/noExplicitAny: Code generated by Better Auth
    }) as Promise<any>,
  // biome-ignore lint/suspicious/noExplicitAny: Code generated by Better Auth
  components: getSchema().then(({ components }) => components) as Promise<any>,
} as const;
