export const ERROR_CODES = {
  SUCCESS: 'SUCCESS',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // Idiom
  IDIOM_PARSE_PINYIN_FAILED: 'IDIOM_PARSE_PINYIN_FAILED',
  IDIOM_ALREADY_EXISTS: 'IDIOM_ALREADY_EXISTS',
  IDIOM_NOT_FOUND: 'IDIOM_NOT_FOUND',
  IDIOM_CSV_EMPTY_OR_MISSING_HEADERS: 'IDIOM_CSV_EMPTY_OR_MISSING_HEADERS',
  IDIOM_CSV_MISSING_TEXT_COLUMN: 'IDIOM_CSV_MISSING_TEXT_COLUMN',
  IDIOM_CSV_EMPTY: 'IDIOM_CSV_EMPTY',
  IDIOM_TEXT_EMPTY: 'IDIOM_TEXT_EMPTY',
  IDIOM_PINYIN_LENGTH_MISMATCH: 'IDIOM_PINYIN_LENGTH_MISMATCH',
  IDIOM_UNRECOGNIZED_PINYIN_TONE: 'IDIOM_UNRECOGNIZED_PINYIN_TONE',
  IDION_DB_BROKEN_DATA: 'IDION_DB_BROKEN_DATA',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
  USER_CANNOT_OPERATE_SELF: 'USER_CANNOT_OPERATE_SELF',
  USER_CANNOT_MODIFY_ADMIN: 'USER_CANNOT_MODIFY_ADMIN',

  // School
  SCHOOL_NOT_FOUND: 'SCHOOL_NOT_FOUND',
  SCHOOL_NAME_ALREADY_EXISTS: 'SCHOOL_NAME_ALREADY_EXISTS',
  SCHOOL_IN_USE: 'SCHOOL_IN_USE',

  // Kungfu
  KUNGFU_NOT_FOUND: 'KUNGFU_NOT_FOUND',
  KUNGFU_NAME_ALREADY_EXISTS: 'KUNGFU_NAME_ALREADY_EXISTS',
  KUNGFU_IN_USE: 'KUNGFU_IN_USE',

  // Game server
  GAME_SERVER_NOT_FOUND: 'GAME_SERVER_NOT_FOUND',
  GAME_SERVER_ID_ALREADY_EXISTS: 'GAME_SERVER_ID_ALREADY_EXISTS',
  GAME_SERVER_ZONE_NAME_ALREADY_EXISTS: 'GAME_SERVER_ZONE_NAME_ALREADY_EXISTS',
  GAME_SERVER_IN_USE: 'GAME_SERVER_IN_USE',

  // Game expansion
  GAME_EXPANSION_NOT_FOUND: 'GAME_EXPANSION_NOT_FOUND',
  GAME_EXPANSION_NAME_ALREADY_EXISTS: 'GAME_EXPANSION_NAME_ALREADY_EXISTS',
  GAME_EXPANSION_IN_USE: 'GAME_EXPANSION_IN_USE',
  GAME_EXPANSION_HAS_SEASONS: 'GAME_EXPANSION_HAS_SEASONS',
  GAME_EXPANSION_DATE_INVALID: 'GAME_EXPANSION_DATE_INVALID',
  GAME_EXPANSION_DATE_CONFLICTS_WITH_SEASONS:
    'GAME_EXPANSION_DATE_CONFLICTS_WITH_SEASONS',

  // Game season
  GAME_SEASON_NOT_FOUND: 'GAME_SEASON_NOT_FOUND',
  GAME_SEASON_NAME_ALREADY_EXISTS: 'GAME_SEASON_NAME_ALREADY_EXISTS',
  GAME_SEASON_IN_USE: 'GAME_SEASON_IN_USE',
  GAME_SEASON_DATE_INVALID: 'GAME_SEASON_DATE_INVALID',
  GAME_SEASON_DATE_OUTSIDE_EXPANSION: 'GAME_SEASON_DATE_OUTSIDE_EXPANSION',
} as const;
