export const ERROR_CODES = {
  SUCCESS: 'SUCCESS',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // Idiom
  IDIOM_PARSE_PINYIN_FAILED: 'IDIOM_PARSE_PINYIN_FAILED',
  IDIOM_ALREADY_EXISTS: 'IDIOM_ALREADY_EXISTS',
  IDIOM_NOT_FOUND: 'IDIOM_NOT_FOUND',
  IDIOM_CSV_EMPTY_OR_MISSING_HEADERS: 'IDIOM_CSV_EMPTY_OR_MISSING_HEADERS',
  IDIOM_CSV_MISSING_TEXT_COLUMN: 'IDIOM_CSV_MISSING_TEXT_COLUMN',
  IDIOM_CSV_EMPTY: 'IDIOM_CSV_EMPTY',
  IDIOM_TEXT_EMPTY: 'IDIOM_TEXT_EMPTY',
  IDIOM_PINYIN_LENGTH_MISMATCH: 'IDIOM_PINYIN_LENGTH_MISMATCH',
  IDIOM_UNRECOGNIZED_PINYIN_TONE: 'IDIOM_UNRECOGNIZED_PINYIN_TONE',
  IDION_DB_BROKEN_DATA: 'IDION_DB_BROKEN_DATA',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
  USER_CANNOT_OPERATE_SELF: 'USER_CANNOT_OPERATE_SELF',
  USER_CANNOT_MODIFY_ADMIN: 'USER_CANNOT_MODIFY_ADMIN',

  // School
  SCHOOL_NOT_FOUND: 'SCHOOL_NOT_FOUND',
  SCHOOL_NAME_ALREADY_EXISTS: 'SCHOOL_NAME_ALREADY_EXISTS',
  SCHOOL_IN_USE: 'SCHOOL_IN_USE',
} as const;
